[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "demucs>=4.0.1",
    "librosa>=0.11.0",
    "numpy>=2.3.5",
    "pedalboard>=0.9.19",
    "sphinx>=9.0.0",
]
